version: "3"
services:
  exelearning-web:
    image: ghcr.io/exelearning/exelearning-web:${EXELEARNING_WEB_CONTAINER_TAG}
    build: ${EXELEARNING_WEB_SOURCECODE_PATH:-}
    ports:
      - ${APP_PORT}:8080
    restart: unless-stopped
    volumes:
      - mnt-data:/mnt/data:rw
    environment:
      APP_ENV: ${APP_ENV}
      APP_DEBUG: ${APP_DEBUG}
      XDEBUG_MODE: ${XDEBUG_MODE}
      APP_SECRET: ${APP_SECRET}
      PRE_CONFIGURE_COMMANDS:
      POST_CONFIGURE_COMMANDS: |
        echo "this is a test line 1"
        echo "this is a test line 2"
        php bin/console app:create-user ${TEST_USER_EMAIL} ${TEST_USER_PASSWORD} ${TEST_USER_USERNAME} --no-fail

  moodle:
    image: erseco/alpine-moodle
    ports:
      - 80:8080
    environment:
      DB_TYPE: mariadb
      DB_HOST: mariadb
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodle
      DB_PREFIX: mdl_
      DEBUG: "true"
      MOODLE_EMAIL: ${TEST_USER_EMAIL}
      MOODLE_LANGUAGE: es
      MOODLE_SITENAME: Moodle-eXeLearning
      MOODLE_USERNAME: ${TEST_USER_USERNAME}
      MOODLE_PASSWORD: ${TEST_USER_PASSWORD}
      PRE_CONFIGURE_COMMANDS: |
        echo 'This is a pre-configure command'
      POST_CONFIGURE_COMMANDS: |
        echo 'This is a post-configure command'
        echo 'Forcing upgrade to re-install exe plugin...'
        php admin/cli/upgrade.php --non-interactive
        php admin/cli/cfg.php --component=exescorm --name=exeonlinebaseuri --set=http://localhost:${APP_PORT}
        php admin/cli/cfg.php --component=exescorm --name=hmackey1 --set=${APP_SECRET}
    depends_on:
      - mariadb
    volumes:
      - moodledata:/var/moodledata

  mariadb:
    image: mariadb:10.6
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  moodledata:
  dbdata:
  mnt-data:
