version: "3"
services:
  moodle:
    image: erseco/alpine-moodle
    ports:
      - 80:8080
    environment:
      DB_TYPE: mariadb
      DB_HOST: mariadb
      DB_NAME: moodle
      DB_USER: moodle
      DB_PASS: moodle
      DB_PORT: 3306
      DB_PREFIX: mdl_
      DEBUG: "true"
      MOODLE_EMAIL: ${TEST_USER_EMAIL}
      MOODLE_LANGUAGE: es
      MOODLE_SITENAME: Moodle-eXeLearning
      MOODLE_USERNAME: ${TEST_USER_USERNAME}
      MOODLE_PASSWORD: ${TEST_USER_PASSWORD}
      PRE_CONFIGURE_COMMANDS: |
        echo 'This is a pre-configure command'
      POST_CONFIGURE_COMMANDS: |
        echo 'This is a post-configure command'
        echo 'Forcing upgrade to re-install exe plugin...'
        php admin/cli/upgrade.php --non-interactive
    depends_on:
      - mariadb
    volumes:
      - moodledata:/var/moodledata
      - .:/var/www/html/contentbank/contenttype/scorm
  mariadb:
    image: mariadb:10.11
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: moodle
      MYSQL_USER: moodle
      MYSQL_PASSWORD: moodle
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  moodledata:
  dbdata:
