name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  build_and_upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set environment variables
        run: |
          RAW_TAG="${GITHUB_REF##*/}"
          VERSION_TAG="${RAW_TAG#v}"
          echo "RELEASE_TAG=${VERSION_TAG}" >> $GITHUB_ENV
      - name: Create package using the Makefile
        run: make package VERSION=${RELEASE_TAG}
      - name: Upload ZIP to the release
        uses: softprops/action-gh-release@v2
        with:
          files: contenttype_scorm-${{ env.RELEASE_TAG }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
